(bind-key* "C-S-V" 'simpleclip-paste)
(bind-key* "C-S-C" 'simpleclip-copy)
(bind-key* "C-S-X" 'simpleclip-cut)
(bind-key* "M-u" 'undo-tree-redo)
(bind-key* "M-+" 'align-regexp)
(bind-key* "M-%" 'anzu-query-replace)
(bind-key* "M-C" 'capitalize-previous-word)
(bind-key* "M-1" 'winum-select-window-1)
(bind-key* "M-2" 'winum-select-window-2)
(bind-key* "M-3" 'winum-select-window-3)
(bind-key* "M-4" 'winum-select-window-4)
(bind-key* "M-5" 'winum-select-window-5)
(bind-key* "M-6" 'winum-select-window-6)
(bind-key* "M-7" 'winum-select-window-7)
(bind-key* "M-8" 'winum-select-window-8)
(bind-key* "M-9" 'winum-select-window-9)

(define-key evil-normal-state-map (kbd "<SPC>qq") 'undefined)
(define-key evil-normal-state-map (kbd "q") 'evil-avy-goto-char)
(evil-define-key 'insert company-active-map (kbd "C-k") 'company-select-previous)

(evil-define-key 'normal helm-map (kbd "<RET>") 'my/helm-exit-minibuffer)
(key-chord-define-global "xs" 'evil-normal-state-and-save)

(provide 'keys)
